// Standard Harmonized System (HS) chapter titles. Pakistan Customs Tariff (PCT)
// codes stored in `export_shipments.pct` follow this same chapter numbering,
// so the leading two digits of a PCT code map directly to one of these.
export const HS_CHAPTERS: Record<string, string> = {
  "01": "Live Animals",
  "02": "Meat and Edible Meat Offal",
  "03": "Fish, Crustaceans and Aquatic Invertebrates",
  "04": "Dairy Produce; Eggs; Honey",
  "05": "Products of Animal Origin, Not Elsewhere Specified",
  "06": "Live Trees and Other Plants; Bulbs, Roots",
  "07": "Edible Vegetables and Certain Roots and Tubers",
  "08": "Edible Fruit and Nuts; Peel of Citrus Fruit or Melons",
  "09": "Coffee, Tea, Mate and Spices",
  "10": "Cereals",
  "11": "Milling Products; Malt; Starches; Inulin",
  "12": "Oil Seeds; Miscellaneous Grains, Seeds and Fruit; Straw and Fodder",
  "13": "Lac; Gums, Resins and Other Vegetable Saps and Extracts",
  "14": "Vegetable Plaiting Materials; Vegetable Products, NES",
  "15": "Animal or Vegetable Fats and Oils",
  "16": "Preparations of Meat, Fish or Crustaceans",
  "17": "Sugars and Sugar Confectionery",
  "18": "Cocoa and Cocoa Preparations",
  "19": "Preparations of Cereals, Flour, Starch or Milk; Bakers' Wares",
  "20": "Preparations of Vegetables, Fruit, Nuts or Other Plants",
  "21": "Miscellaneous Edible Preparations",
  "22": "Beverages, Spirits and Vinegar",
  "23": "Residues and Waste from the Food Industries; Animal Feed",
  "24": "Tobacco and Manufactured Tobacco Substitutes",
  "25": "Salt; Sulphur; Earths and Stone; Plastering Materials, Lime and Cement",
  "26": "Ores, Slag and Ash",
  "27": "Mineral Fuels, Oils and Products of Their Distillation",
  "28": "Inorganic Chemicals",
  "29": "Organic Chemicals",
  "30": "Pharmaceutical Products",
  "31": "Fertilisers",
  "32": "Tanning or Dyeing Extracts; Paints and Varnishes",
  "33": "Essential Oils and Resinoids; Perfumery and Cosmetic Preparations",
  "34": "Soap, Washing Preparations, Lubricants, Waxes, Candles",
  "35": "Albuminoidal Substances; Starches; Glues; Enzymes",
  "36": "Explosives; Pyrotechnic Products; Matches",
  "37": "Photographic or Cinematographic Goods",
  "38": "Miscellaneous Chemical Products",
  "39": "Plastics and Articles Thereof",
  "40": "Rubber and Articles Thereof",
  "41": "Raw Hides and Skins (Other than Furskins) and Leather",
  "42": "Articles of Leather; Saddlery and Harness; Travel Goods, Handbags",
  "43": "Furskins and Artificial Fur; Manufactures Thereof",
  "44": "Wood and Articles of Wood; Wood Charcoal",
  "45": "Cork and Articles of Cork",
  "46": "Manufactures of Straw, Esparto or Other Plaiting Materials",
  "47": "Pulp of Wood or Other Fibrous Cellulosic Material",
  "48": "Paper and Paperboard; Articles Thereof",
  "49": "Printed Books, Newspapers, Pictures and Other Printing Products",
  "50": "Silk",
  "51": "Wool, Fine Animal Hair; Horsehair Yarn and Woven Fabric",
  "52": "Cotton",
  "53": "Other Vegetable Textile Fibres; Paper Yarn and Woven Fabric",
  "54": "Man-Made Filaments; Strip of Man-Made Textile Materials",
  "55": "Man-Made Staple Fibres",
  "56": "Wadding, Felt and Nonwovens; Twine, Cordage, Ropes and Cables",
  "57": "Carpets and Other Textile Floor Coverings",
  "58": "Special Woven Fabrics; Tufted Textile Fabrics; Lace; Tapestries",
  "59": "Impregnated, Coated, Covered or Laminated Textile Fabrics",
  "60": "Knitted or Crocheted Fabrics",
  "61": "Articles of Apparel and Clothing Accessories, Knitted or Crocheted",
  "62": "Articles of Apparel and Clothing Accessories, Not Knitted or Crocheted",
  "63": "Other Made Up Textile Articles; Sets; Worn Clothing",
  "64": "Footwear, Gaiters and the Like; Parts Thereof",
  "65": "Headgear and Parts Thereof",
  "66": "Umbrellas, Sun Umbrellas, Walking Sticks, Whips",
  "67": "Prepared Feathers and Down; Artificial Flowers",
  "68": "Articles of Stone, Plaster, Cement, Asbestos, Mica",
  "69": "Ceramic Products",
  "70": "Glass and Glassware",
  "71": "Natural or Cultured Pearls, Precious Stones, Jewellery",
  "72": "Iron and Steel",
  "73": "Articles of Iron or Steel",
  "74": "Copper and Articles Thereof",
  "75": "Nickel and Articles Thereof",
  "76": "Aluminium and Articles Thereof",
  "78": "Lead and Articles Thereof",
  "79": "Zinc and Articles Thereof",
  "80": "Tin and Articles Thereof",
  "81": "Other Base Metals; Cermets; Articles Thereof",
  "82": "Tools, Implements, Cutlery, Spoons and Forks, of Base Metal",
  "83": "Miscellaneous Articles of Base Metal",
  "84": "Machinery and Mechanical Appliances; Parts Thereof",
  "85": "Electrical Machinery and Equipment and Parts Thereof",
  "86": "Railway or Tramway Locomotives, Rolling-Stock and Parts",
  "87": "Vehicles Other than Railway or Tramway Rolling-Stock",
  "88": "Aircraft, Spacecraft, and Parts Thereof",
  "89": "Ships, Boats and Floating Structures",
  "90": "Optical, Photographic, Medical or Surgical Instruments",
  "91": "Clocks and Watches and Parts Thereof",
  "92": "Musical Instruments; Parts and Accessories",
  "93": "Arms and Ammunition; Parts and Accessories",
  "94": "Furniture; Bedding, Mattresses; Lamps and Lighting Fittings",
  "95": "Toys, Games and Sports Requisites; Parts and Accessories",
  "96": "Miscellaneous Manufactured Articles",
  "97": "Works of Art, Collectors' Pieces and Antiques",
};

export function getCategoryLabel(chapter: string): string {
  return HS_CHAPTERS[chapter] ?? `Other (Category ${chapter})`;
}

// Postgres expression that derives the 2-digit HS/PCT chapter from the
// numeric `pct` column, e.g. 6101.2 -> "61", 201.1 -> "02".
export const CHAPTER_SQL_EXPR = "LEFT(LPAD(FLOOR(pct)::bigint::text, 4, '0'), 2)";
