"use client";

import React, { useEffect, useState } from "react";
import { FileText, Calendar, DollarSign } from "lucide-react";

type InvoiceRecord = {
  id: number;
  invoice_no: string;
  doc_type: string;
  buyer_name: string;
  total_value: string | number;
  admin_name: string;
  created_at: string;
};

export default function InvoiceRecordsPage() {
  const [records, setRecords] = useState<InvoiceRecord[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch('/api/admin/invoices/record')
      .then(res => res.json())
      .then(data => {
        if (data.records) setRecords(data.records);
        setLoading(false);
      })
      .catch(err => {
        console.error("Failed to fetch records", err);
        setLoading(false);
      });
  }, []);

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-bold text-gray-900 tracking-tight">Invoice Records</h1>
        <p className="text-gray-500 mt-2">Log of all trade documents generated and exported by administrators.</p>
      </div>

      <div className="bg-white rounded-2xl shadow-sm border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="w-full text-left text-sm text-gray-600">
            <thead className="bg-gray-50 text-gray-500 text-xs uppercase tracking-wider">
              <tr>
                <th className="px-6 py-4 font-semibold">Document No</th>
                <th className="px-6 py-4 font-semibold">Type</th>
                <th className="px-6 py-4 font-semibold">Buyer</th>
                <th className="px-6 py-4 font-semibold">Total Value</th>
                <th className="px-6 py-4 font-semibold">Generated By</th>
                <th className="px-6 py-4 font-semibold">Date</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
              {loading ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500">Loading records...</td>
                </tr>
              ) : records.length === 0 ? (
                <tr>
                  <td colSpan={6} className="px-6 py-8 text-center text-gray-500">No invoices have been generated yet.</td>
                </tr>
              ) : (
                records.map((record) => (
                  <tr key={record.id} className="hover:bg-gray-50/50 transition-colors">
                    <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900 flex items-center gap-2">
                      <a href={`/dashboard/admin/invoices?record_id=${record.id}`} className="flex items-center gap-2 hover:text-blue-600 transition-colors cursor-pointer" title="Open Invoice">
                        <FileText size={16} className="text-blue-500" />
                        {record.invoice_no}
                      </a>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <span className="px-2.5 py-1 bg-blue-50 text-blue-700 rounded-lg text-xs font-medium">
                        {record.doc_type}
                      </span>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      {record.buyer_name}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap font-medium text-gray-900 flex items-center gap-1">
                      <DollarSign size={14} className="text-gray-400" />
                      {Number(record.total_value).toLocaleString('en-US', { minimumFractionDigits: 2 })}
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap">
                      <div className="flex items-center gap-2">
                        <div className="w-6 h-6 rounded-full bg-indigo-100 text-indigo-600 flex items-center justify-center text-xs font-bold">
                          {record.admin_name.charAt(0)}
                        </div>
                        {record.admin_name}
                      </div>
                    </td>
                    <td className="px-6 py-4 whitespace-nowrap text-gray-500 flex items-center gap-1.5">
                      <Calendar size={14} />
                      {new Date(record.created_at).toLocaleString()}
                    </td>
                  </tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
